# TO DO:
# 1. Move Log textEdit down with text
# 2. Add thread for continiuos reading of incomming data of Mudbus
# 3. Plots
# 4. Logging
# 5. Add QtCore to use its time and date for logging. could be miliseconds:)
# 6. Implement auto repeat function for buttons
# 7. Icons for buttons/lables?
# 8. Group radiobutton

# for lineedit:
# 9. setplaceholdertext - set grey hint
# 10. set readonly
# 11. add standart messages
# 12. add function, when leave set angle -> adding degree symbol

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QObject, QThread, pyqtSignal
from modbus import *
import time
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas


class Plot(FigureCanvas):
    def __init__(self, parent):
        self.parent = parent
        self.fig, self.ax = plt.subplots(figsize=(4.8, 2.3), tight_layout=True, dpi=100)
        self.fig.patch.set_facecolor('#F0F0F0')  # make a color the same as the background
        self.x = np.linspace(0, 10, 100)
        self.y = 3*np.sin(self.x*2) + 5

        self.ax.set(xlim=(0, 10), ylim=(0, 10), xticks=np.arange(0, 10), yticks=np.arange(0, 10))
        self.ax.set_xlabel("Time, [ms]", fontsize=8)
        self.ax.set_ylabel("Angle, [deg]", fontsize=8)
        self.ax.set_title("Joint's Position", fontsize=10)
        self.ax.tick_params(axis='both', which='major', labelsize=6)
        self.ax.grid(True, linestyle=':', linewidth=0.6)
        super().__init__(self.fig)
        self.setParent(self.parent)
        self.update_plot()

    def update_plot(self):
        # make data
        # plot
        # plt.style.use('fivethirtyeight')

        self.ax.plot(self.x, self.y, linewidth=1.0, label='Angle', color='#03dfd5')
        self.ax.legend(loc=1, fontsize=8)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1200, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        MainWindow.setWindowOpacity(0.98)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Germany))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks|QtWidgets.QMainWindow.VerticalTabs)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.slaveidspinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.slaveidspinBox.setGeometry(QtCore.QRect(170, 10, 51, 20))
        self.slaveidspinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.slaveidspinBox.setProperty("value", 1)
        self.slaveidspinBox.setObjectName("slaveidspinBox")
        self.slaveidlable = QtWidgets.QLabel(self.centralwidget)
        self.slaveidlable.setGeometry(QtCore.QRect(70, 10, 70, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.slaveidlable.setFont(font)
        self.slaveidlable.setObjectName("slaveidlable")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(280, 210, 381, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(260, 10, 20, 731))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButton_readallstatus = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_readallstatus.setGeometry(QtCore.QRect(530, 140, 121, 21))
        self.pushButton_readallstatus.setObjectName("pushButton_readallstatus")
        self.textEdit_log = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_log.setGeometry(QtCore.QRect(10, 420, 241, 321))
        self.textEdit_log.setObjectName("textEdit_log")
        self.loglable = QtWidgets.QLabel(self.centralwidget)
        self.loglable.setGeometry(QtCore.QRect(20, 400, 160, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.loglable.setFont(font)
        self.loglable.setObjectName("loglable")
        self.jcuinputreglable = QtWidgets.QLabel(self.centralwidget)
        self.jcuinputreglable.setEnabled(True)
        self.jcuinputreglable.setGeometry(QtCore.QRect(430, 10, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.jcuinputreglable.setFont(font)
        self.jcuinputreglable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.jcuinputreglable.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Germany))
        self.jcuinputreglable.setObjectName("jcuinputreglable")
        self.jcuholdreglable = QtWidgets.QLabel(self.centralwidget)
        self.jcuholdreglable.setEnabled(True)
        self.jcuholdreglable.setGeometry(QtCore.QRect(410, 230, 160, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.jcuholdreglable.setFont(font)
        self.jcuholdreglable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.jcuholdreglable.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Germany))
        self.jcuholdreglable.setObjectName("jcuholdreglable")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(660, 10, 20, 731))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.pushButton_readsinglestatus = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_readsinglestatus.setGeometry(QtCore.QRect(530, 40, 121, 21))
        self.pushButton_readsinglestatus.setObjectName("pushButton_readsinglestatus")
        self.pushButton_readsingleconfig = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_readsingleconfig.setGeometry(QtCore.QRect(530, 270, 121, 21))
        self.pushButton_readsingleconfig.setObjectName("pushButton_readsingleconfig")
        self.pushButton_readallconfig = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_readallconfig.setGeometry(QtCore.QRect(530, 540, 121, 21))
        self.pushButton_readallconfig.setObjectName("pushButton_readallconfig")
        self.pushButton_writeallconfig = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_writeallconfig.setGeometry(QtCore.QRect(530, 570, 121, 21))
        self.pushButton_writeallconfig.setObjectName("pushButton_writeallconfig")
        self.pushButton_writesingleconfig = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_writesingleconfig.setGeometry(QtCore.QRect(530, 300, 121, 21))
        self.pushButton_writesingleconfig.setObjectName("pushButton_writesingleconfig")
        self.lable_errors_2 = QtWidgets.QLabel(self.centralwidget)
        self.lable_errors_2.setGeometry(QtCore.QRect(300, 690, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_errors_2.setFont(font)
        self.lable_errors_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_errors_2.setObjectName("lable_errors_2")
        self.lable_statreg_2 = QtWidgets.QLabel(self.centralwidget)
        self.lable_statreg_2.setGeometry(QtCore.QRect(300, 720, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_statreg_2.setFont(font)
        self.lable_statreg_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_statreg_2.setObjectName("lable_statreg_2")
        self.pushButton_enablemotor = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_enablemotor.setGeometry(QtCore.QRect(20, 80, 121, 21))
        self.pushButton_enablemotor.setObjectName("pushButton_enablemotor")
        self.dial_angle = QtWidgets.QDial(self.centralwidget)
        self.dial_angle.setGeometry(QtCore.QRect(0, 240, 141, 131))
        self.dial_angle.setInputMethodHints(QtCore.Qt.ImhNone)
        self.dial_angle.setMaximum(4095)
        self.dial_angle.setSingleStep(1)
        self.dial_angle.setPageStep(0)
        self.dial_angle.setOrientation(QtCore.Qt.Horizontal)
        self.dial_angle.setWrapping(True)
        self.dial_angle.setNotchTarget(90.0)
        self.dial_angle.setNotchesVisible(True)
        self.dial_angle.setObjectName("dial_angle")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(532, 110, 101, 20))
        self.checkBox.setObjectName("checkBox")
        self.pushButton_break = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_break.setGeometry(QtCore.QRect(20, 110, 121, 21))
        self.pushButton_break.setObjectName("pushButton_break")
        self.checkBox_follow = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_follow.setGeometry(QtCore.QRect(150, 260, 121, 20))
        self.checkBox_follow.setObjectName("checkBox_follow")
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(20, 140, 121, 21))
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_stop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_stop.setGeometry(QtCore.QRect(20, 170, 121, 21))
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(720, 20, 451, 201))
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(690, 240, 500, 250))
        self.widget_2.setObjectName("widget_2")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(720, 460, 451, 201))
        self.widget_3.setObjectName("widget_3")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, 210, 251, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(300, 270, 211, 394))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_ki_pos = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_ki_pos.setText("")
        self.lineEdit_ki_pos.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_ki_pos.setObjectName("lineEdit_ki_pos")
        self.gridLayout.addWidget(self.lineEdit_ki_pos, 10, 0, 1, 1)
        self.radioButton_statusreg = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_statusreg.setText("")
        self.radioButton_statusreg.setObjectName("radioButton_statusreg")
        self.gridLayout.addWidget(self.radioButton_statusreg, 5, 1, 1, 1)
        self.radioButton_kpspeed = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_kpspeed.setText("")
        self.radioButton_kpspeed.setObjectName("radioButton_kpspeed")
        self.gridLayout.addWidget(self.radioButton_kpspeed, 12, 1, 1, 1)
        self.radioButton_targetangle = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_targetangle.setText("")
        self.radioButton_targetangle.setAutoExclusive(True)
        self.radioButton_targetangle.setObjectName("radioButton_targetangle")
        self.gridLayout.addWidget(self.radioButton_targetangle, 4, 1, 1, 1)
        self.lineEdit_ki_speed = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_ki_speed.setText("")
        self.lineEdit_ki_speed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_ki_speed.setObjectName("lineEdit_ki_speed")
        self.gridLayout.addWidget(self.lineEdit_ki_speed, 13, 0, 1, 1)
        self.radioButton_maxspeedtorque = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_maxspeedtorque.setText("")
        self.radioButton_maxspeedtorque.setObjectName("radioButton_maxspeedtorque")
        self.gridLayout.addWidget(self.radioButton_maxspeedtorque, 2, 1, 2, 1)
        self.lineEdit_maxtorque = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_maxtorque.setText("")
        self.lineEdit_maxtorque.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_maxtorque.setObjectName("lineEdit_maxtorque")
        self.gridLayout.addWidget(self.lineEdit_maxtorque, 3, 0, 1, 1)
        self.lineEdit_targetangle = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_targetangle.setText("")
        self.lineEdit_targetangle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_targetangle.setObjectName("lineEdit_targetangle")
        self.gridLayout.addWidget(self.lineEdit_targetangle, 4, 0, 1, 1)
        self.radioButton_accel = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_accel.setText("")
        self.radioButton_accel.setObjectName("radioButton_accel")
        self.gridLayout.addWidget(self.radioButton_accel, 0, 1, 2, 1)
        self.lineEdit_kp_current = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_kp_current.setText("")
        self.lineEdit_kp_current.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_kp_current.setObjectName("lineEdit_kp_current")
        self.gridLayout.addWidget(self.lineEdit_kp_current, 6, 0, 1, 1)
        self.lineEdit_kd_current = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_kd_current.setEnabled(False)
        self.lineEdit_kd_current.setText("")
        self.lineEdit_kd_current.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_kd_current.setObjectName("lineEdit_kd_current")
        self.gridLayout.addWidget(self.lineEdit_kd_current, 8, 0, 1, 1)
        self.radioButton_kdcurrent = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_kdcurrent.setEnabled(False)
        self.radioButton_kdcurrent.setText("")
        self.radioButton_kdcurrent.setObjectName("radioButton_kdcurrent")
        self.gridLayout.addWidget(self.radioButton_kdcurrent, 8, 1, 1, 1)
        self.lineEdit_kp_pos = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_kp_pos.setText("")
        self.lineEdit_kp_pos.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_kp_pos.setObjectName("lineEdit_kp_pos")
        self.gridLayout.addWidget(self.lineEdit_kp_pos, 9, 0, 1, 1)
        self.radioButton_kpposition = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_kpposition.setText("")
        self.radioButton_kpposition.setObjectName("radioButton_kpposition")
        self.gridLayout.addWidget(self.radioButton_kpposition, 9, 1, 1, 1)
        self.lineEdit_acceleration = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_acceleration.setText("")
        self.lineEdit_acceleration.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_acceleration.setObjectName("lineEdit_acceleration")
        self.gridLayout.addWidget(self.lineEdit_acceleration, 0, 0, 1, 1)
        self.lineEdit_statreg = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_statreg.setText("")
        self.lineEdit_statreg.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_statreg.setObjectName("lineEdit_statreg")
        self.gridLayout.addWidget(self.lineEdit_statreg, 5, 0, 1, 1)
        self.radioButton_kiposition = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_kiposition.setText("")
        self.radioButton_kiposition.setObjectName("radioButton_kiposition")
        self.gridLayout.addWidget(self.radioButton_kiposition, 10, 1, 1, 1)
        self.lineEdit_kd_pos = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_kd_pos.setText("")
        self.lineEdit_kd_pos.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_kd_pos.setObjectName("lineEdit_kd_pos")
        self.gridLayout.addWidget(self.lineEdit_kd_pos, 11, 0, 1, 1)
        self.radioButton_kdposition = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_kdposition.setText("")
        self.radioButton_kdposition.setObjectName("radioButton_kdposition")
        self.gridLayout.addWidget(self.radioButton_kdposition, 11, 1, 1, 1)
        self.lineEdit_maxspeed = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_maxspeed.setText("")
        self.lineEdit_maxspeed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_maxspeed.setObjectName("lineEdit_maxspeed")
        self.gridLayout.addWidget(self.lineEdit_maxspeed, 2, 0, 1, 1)
        self.radioButton_kpcurrent = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_kpcurrent.setText("")
        self.radioButton_kpcurrent.setObjectName("radioButton_kpcurrent")
        self.gridLayout.addWidget(self.radioButton_kpcurrent, 6, 1, 1, 1)
        self.lineEdit_deceleration = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_deceleration.setText("")
        self.lineEdit_deceleration.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_deceleration.setObjectName("lineEdit_deceleration")
        self.gridLayout.addWidget(self.lineEdit_deceleration, 1, 0, 1, 1)
        self.lineEdit_ki_current = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_ki_current.setText("")
        self.lineEdit_ki_current.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_ki_current.setObjectName("lineEdit_ki_current")
        self.gridLayout.addWidget(self.lineEdit_ki_current, 7, 0, 1, 1)
        self.radioButton_kicurrent = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_kicurrent.setText("")
        self.radioButton_kicurrent.setObjectName("radioButton_kicurrent")
        self.gridLayout.addWidget(self.radioButton_kicurrent, 7, 1, 1, 1)
        self.lineEdit_kp_speed = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_kp_speed.setText("")
        self.lineEdit_kp_speed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_kp_speed.setObjectName("lineEdit_kp_speed")
        self.gridLayout.addWidget(self.lineEdit_kp_speed, 12, 0, 1, 1)
        self.radioButton_kdspeed = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_kdspeed.setText("")
        self.radioButton_kdspeed.setObjectName("radioButton_kdspeed")
        self.gridLayout.addWidget(self.radioButton_kdspeed, 14, 1, 1, 1)
        self.lineEdit_kd_speed = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_kd_speed.setText("")
        self.lineEdit_kd_speed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_kd_speed.setObjectName("lineEdit_kd_speed")
        self.gridLayout.addWidget(self.lineEdit_kd_speed, 14, 0, 1, 1)
        self.radioButton_kispeed = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_kispeed.setText("")
        self.radioButton_kispeed.setObjectName("radioButton_kispeed")
        self.gridLayout.addWidget(self.radioButton_kispeed, 13, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 15, 1)
        self.lable_deceleration = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_deceleration.setFont(font)
        self.lable_deceleration.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_deceleration.setObjectName("lable_deceleration")
        self.gridLayout_2.addWidget(self.lable_deceleration, 1, 0, 1, 1)
        self.lable_maxspeed = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_maxspeed.setFont(font)
        self.lable_maxspeed.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_maxspeed.setObjectName("lable_maxspeed")
        self.gridLayout_2.addWidget(self.lable_maxspeed, 2, 0, 1, 1)
        self.lable_maxtorque = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_maxtorque.setFont(font)
        self.lable_maxtorque.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_maxtorque.setObjectName("lable_maxtorque")
        self.gridLayout_2.addWidget(self.lable_maxtorque, 3, 0, 1, 1)
        self.lable_targetangle = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_targetangle.setFont(font)
        self.lable_targetangle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_targetangle.setObjectName("lable_targetangle")
        self.gridLayout_2.addWidget(self.lable_targetangle, 4, 0, 1, 1)
        self.lable_statreg = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_statreg.setFont(font)
        self.lable_statreg.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_statreg.setObjectName("lable_statreg")
        self.gridLayout_2.addWidget(self.lable_statreg, 5, 0, 1, 1)
        self.lable_kp_current = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_kp_current.setFont(font)
        self.lable_kp_current.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_kp_current.setObjectName("lable_kp_current")
        self.gridLayout_2.addWidget(self.lable_kp_current, 6, 0, 1, 1)
        self.lable_ki_current = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_ki_current.setFont(font)
        self.lable_ki_current.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_ki_current.setObjectName("lable_ki_current")
        self.gridLayout_2.addWidget(self.lable_ki_current, 7, 0, 1, 1)
        self.lable_kd_current = QtWidgets.QLabel(self.layoutWidget)
        self.lable_kd_current.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_kd_current.setFont(font)
        self.lable_kd_current.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_kd_current.setObjectName("lable_kd_current")
        self.gridLayout_2.addWidget(self.lable_kd_current, 8, 0, 1, 1)
        self.lable_kp_pos = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_kp_pos.setFont(font)
        self.lable_kp_pos.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_kp_pos.setObjectName("lable_kp_pos")
        self.gridLayout_2.addWidget(self.lable_kp_pos, 9, 0, 1, 1)
        self.lable_ki_pos = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_ki_pos.setFont(font)
        self.lable_ki_pos.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_ki_pos.setObjectName("lable_ki_pos")
        self.gridLayout_2.addWidget(self.lable_ki_pos, 10, 0, 1, 1)
        self.lable_kd_pos = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_kd_pos.setFont(font)
        self.lable_kd_pos.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_kd_pos.setObjectName("lable_kd_pos")
        self.gridLayout_2.addWidget(self.lable_kd_pos, 11, 0, 1, 1)
        self.lable_kp_speed = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_kp_speed.setFont(font)
        self.lable_kp_speed.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_kp_speed.setObjectName("lable_kp_speed")
        self.gridLayout_2.addWidget(self.lable_kp_speed, 12, 0, 1, 1)
        self.lable_ki_speed = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_ki_speed.setFont(font)
        self.lable_ki_speed.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_ki_speed.setObjectName("lable_ki_speed")
        self.gridLayout_2.addWidget(self.lable_ki_speed, 13, 0, 1, 1)
        self.lable_kd_speed = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_kd_speed.setFont(font)
        self.lable_kd_speed.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_kd_speed.setObjectName("lable_kd_speed")
        self.gridLayout_2.addWidget(self.lable_kd_speed, 14, 0, 1, 1)
        self.lable_acceleration = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_acceleration.setFont(font)
        self.lable_acceleration.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_acceleration.setObjectName("lable_acceleration")
        self.gridLayout_2.addWidget(self.lable_acceleration, 0, 0, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(301, 41, 211, 152))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_drivertemp = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_drivertemp.setText("")
        self.lineEdit_drivertemp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_drivertemp.setObjectName("lineEdit_drivertemp")
        self.gridLayout_3.addWidget(self.lineEdit_drivertemp, 5, 1, 1, 1)
        self.radioButton_drivertemp = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioButton_drivertemp.setText("")
        self.radioButton_drivertemp.setObjectName("radioButton_drivertemp")
        self.gridLayout_3.addWidget(self.radioButton_drivertemp, 5, 2, 1, 1)
        self.lineEdit_errors = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_errors.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_errors.setText("")
        self.lineEdit_errors.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_errors.setObjectName("lineEdit_errors")
        self.gridLayout_3.addWidget(self.lineEdit_errors, 0, 1, 1, 1)
        self.lable_torque = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_torque.setFont(font)
        self.lable_torque.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_torque.setObjectName("lable_torque")
        self.gridLayout_3.addWidget(self.lable_torque, 3, 0, 1, 1)
        self.lineEdit_torque = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_torque.setText("")
        self.lineEdit_torque.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_torque.setObjectName("lineEdit_torque")
        self.gridLayout_3.addWidget(self.lineEdit_torque, 3, 1, 1, 1)
        self.radioButton_angle = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioButton_angle.setText("")
        self.radioButton_angle.setObjectName("radioButton_angle")
        self.gridLayout_3.addWidget(self.radioButton_angle, 1, 2, 1, 1)
        self.radioButton_errors = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioButton_errors.setText("")
        self.radioButton_errors.setCheckable(True)
        self.radioButton_errors.setChecked(False)
        self.radioButton_errors.setAutoRepeat(False)
        self.radioButton_errors.setObjectName("radioButton_errors")
        self.gridLayout_3.addWidget(self.radioButton_errors, 0, 2, 1, 1)
        self.radioButton_torque = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioButton_torque.setText("")
        self.radioButton_torque.setObjectName("radioButton_torque")
        self.gridLayout_3.addWidget(self.radioButton_torque, 3, 2, 1, 1)
        self.lable_drivertemp = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_drivertemp.setFont(font)
        self.lable_drivertemp.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_drivertemp.setObjectName("lable_drivertemp")
        self.gridLayout_3.addWidget(self.lable_drivertemp, 5, 0, 1, 1)
        self.lable_speed = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_speed.setFont(font)
        self.lable_speed.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_speed.setObjectName("lable_speed")
        self.gridLayout_3.addWidget(self.lable_speed, 2, 0, 1, 1)
        self.lable_motortemp = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_motortemp.setFont(font)
        self.lable_motortemp.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_motortemp.setObjectName("lable_motortemp")
        self.gridLayout_3.addWidget(self.lable_motortemp, 4, 0, 1, 1)
        self.lable_errors = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_errors.setFont(font)
        self.lable_errors.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lable_errors.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_errors.setObjectName("lable_errors")
        self.gridLayout_3.addWidget(self.lable_errors, 0, 0, 1, 1)
        self.lineEdit_angle = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_angle.setText("")
        self.lineEdit_angle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_angle.setObjectName("lineEdit_angle")
        self.gridLayout_3.addWidget(self.lineEdit_angle, 1, 1, 1, 1)
        self.lineEdit_speed = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_speed.setText("")
        self.lineEdit_speed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_speed.setObjectName("lineEdit_speed")
        self.gridLayout_3.addWidget(self.lineEdit_speed, 2, 1, 1, 1)
        self.lable_angle = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lable_angle.sizePolicy().hasHeightForWidth())
        self.lable_angle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_angle.setFont(font)
        self.lable_angle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_angle.setObjectName("lable_angle")
        self.gridLayout_3.addWidget(self.lable_angle, 1, 0, 1, 1)
        self.radioButton_speed = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioButton_speed.setText("")
        self.radioButton_speed.setObjectName("radioButton_speed")
        self.gridLayout_3.addWidget(self.radioButton_speed, 2, 2, 1, 1)
        self.lineEdit_motortemp = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_motortemp.setText("")
        self.lineEdit_motortemp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_motortemp.setObjectName("lineEdit_motortemp")
        self.gridLayout_3.addWidget(self.lineEdit_motortemp, 4, 1, 1, 1)
        self.radioButton_mottemp = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioButton_mottemp.setText("")
        self.radioButton_mottemp.setObjectName("radioButton_mottemp")
        self.gridLayout_3.addWidget(self.radioButton_mottemp, 4, 2, 1, 1)
        self.pushButton_connect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_connect.setGeometry(QtCore.QRect(60, 40, 171, 21))
        self.pushButton_connect.setObjectName("pushButton_connect")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuLog = QtWidgets.QMenu(self.menubar)
        self.menuLog.setObjectName("menuLog")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAbout_2 = QtWidgets.QAction(MainWindow)
        self.actionAbout_2.setObjectName("actionAbout_2")
        self.actionSerial_config = QtWidgets.QAction(MainWindow)
        self.actionSerial_config.setObjectName("actionSerial_config")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionJCU_Register_Info = QtWidgets.QAction(MainWindow)
        self.actionJCU_Register_Info.setObjectName("actionJCU_Register_Info")
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addAction(self.actionJCU_Register_Info)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuLog.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.slaveidlable.setText(_translate("MainWindow", "Slave ID:"))
        self.pushButton_readallstatus.setText(_translate("MainWindow", "Read All"))
        self.loglable.setText(_translate("MainWindow", "Log:"))
        self.jcuinputreglable.setText(_translate("MainWindow", "JCU Status"))
        self.jcuholdreglable.setText(_translate("MainWindow", "JCU Configuration"))
        self.pushButton_readsinglestatus.setText(_translate("MainWindow", "Read Single"))
        self.pushButton_readsingleconfig.setText(_translate("MainWindow", "Read Single"))
        self.pushButton_readallconfig.setText(_translate("MainWindow", "Read All"))
        self.pushButton_writeallconfig.setText(_translate("MainWindow", "Write All"))
        self.pushButton_writesingleconfig.setText(_translate("MainWindow", "Write Single"))
        self.lable_errors_2.setText(_translate("MainWindow", "Errors"))
        self.lable_statreg_2.setText(_translate("MainWindow", "Status register"))
        self.pushButton_enablemotor.setText(_translate("MainWindow", "Enable Motor"))
        self.checkBox.setText(_translate("MainWindow", "Continious Read"))
        self.pushButton_break.setText(_translate("MainWindow", "Brake"))
        self.checkBox_follow.setText(_translate("MainWindow", "Follow in Real Time"))
        self.pushButton_start.setText(_translate("MainWindow", "Start"))
        self.pushButton_stop.setText(_translate("MainWindow", "Stop"))
        self.lable_deceleration.setText(_translate("MainWindow", "Deceleration"))
        self.lable_maxspeed.setText(_translate("MainWindow", "Max speed"))
        self.lable_maxtorque.setText(_translate("MainWindow", "Max torque"))
        self.lable_targetangle.setText(_translate("MainWindow", "Target Angle"))
        self.lable_statreg.setText(_translate("MainWindow", "Status register"))
        self.lable_kp_current.setText(_translate("MainWindow", "Kp (current)"))
        self.lable_ki_current.setText(_translate("MainWindow", "Ki (current)"))
        self.lable_kd_current.setText(_translate("MainWindow", "Kd (current)"))
        self.lable_kp_pos.setText(_translate("MainWindow", "Kp (position)"))
        self.lable_ki_pos.setText(_translate("MainWindow", "Ki (position)"))
        self.lable_kd_pos.setText(_translate("MainWindow", "Kd (position)"))
        self.lable_kp_speed.setText(_translate("MainWindow", "Kp (speed)"))
        self.lable_ki_speed.setText(_translate("MainWindow", "Ki (speed)"))
        self.lable_kd_speed.setText(_translate("MainWindow", "Kd (speed)"))
        self.lable_acceleration.setText(_translate("MainWindow", "Acceleration"))
        self.lable_torque.setText(_translate("MainWindow", "Torque"))
        self.lable_drivertemp.setText(_translate("MainWindow", "Driver temp"))
        self.lable_speed.setText(_translate("MainWindow", "Speed"))
        self.lable_motortemp.setText(_translate("MainWindow", "Motor temp     "))
        self.lable_errors.setText(_translate("MainWindow", "Errors"))
        self.lable_angle.setText(_translate("MainWindow", "Angle"))
        self.pushButton_connect.setText(_translate("MainWindow", "Connect"))
        self.menuFile.setTitle(_translate("MainWindow", "Settings"))
        self.menuLog.setTitle(_translate("MainWindow", "Help"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAbout_2.setText(_translate("MainWindow", "About"))
        self.actionSerial_config.setText(_translate("MainWindow", "Serial config"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionJCU_Register_Info.setText(_translate("MainWindow", "JCU Register Info"))

        # user code begins here
        Plot(self.widget_2)
        # default values:
        self.lineEdit_targetangle.setText("0°")

        # actions
        self.pushButton_enablemotor.clicked.connect(self.enable_motor)
        self.dial_angle.valueChanged.connect(self.update_target_angle_lable)
        self.pushButton_connect.clicked.connect(self.connect_device)
        self.pushButton_readsinglestatus.clicked.connect(self.read_single_status_register)
        self.pushButton_readallstatus.clicked.connect(self.read_single_all_status_registers)
        self.pushButton_writesingleconfig.clicked.connect(self.write_single_register)


    def get_time(self):
        self.currenttime = time.strftime("%H:%M:%S", time.localtime())
        return self.currenttime

    def connect_device(self):
        open_com()
        self.textEdit_log.append(f"- {self.get_time()}: Device 01 has been connected")

    def read_single_status_register(self):
        if  self.radioButton_errors.isChecked():
            self.slave_response = modbus_read_registers(modbus_function = 4, register_address = 30001, amount_of_read = 1)
            self.textEdit_log.append(f"- {self.get_time()}: Slave response: {hex(self.slave_response[0])}")
            self.lineEdit_errors.setText(f"{self.slave_response[0]}")

        elif self.radioButton_angle.isChecked():
            self.slave_response = modbus_read_registers(modbus_function = 4, register_address = 30002, amount_of_read = 1)
            self.textEdit_log.append(f"- {self.get_time()}: Slave response: {hex(self.slave_response[0])}")
            self.lineEdit_angle.setText(f"{self.slave_response[0]}")

        elif self.radioButton_speed.isChecked():
            self.slave_response = modbus_read_registers(modbus_function = 4, register_address = 30003, amount_of_read = 1)
            self.textEdit_log.append(f"- {self.get_time()}: Slave response: {hex(self.slave_response[0])}")
            self.lineEdit_speed.setText(f"{self.slave_response[0]}")

        elif self.radioButton_torque.isChecked():
            self.slave_response = modbus_read_registers(modbus_function = 4, register_address = 30004, amount_of_read = 1)
            self.textEdit_log.append(f"- {self.get_time()}: Slave response: {hex(self.slave_response[0])}")
            self.lineEdit_torque.setText(f"{self.slave_response[0]}")

        elif self.radioButton_mottemp.isChecked():
            self.slave_response = modbus_read_registers(modbus_function = 4, register_address = 30005, amount_of_read = 1)
            self.temp = divmod(self.slave_response[0], 0x100)
            self.textEdit_log.append(f"- {self.get_time()}: Slave response: {hex(self.slave_response[0])}")
            self.lineEdit_motortemp.setText(str(self.temp[1]))
            self.lineEdit_drivertemp.setText(str(self.temp[0]))
        else:
            self.textEdit_log.setTextColor(redColor)
            self.textEdit_log.append(f"- {self.get_time()}: Select register to read!")
            self.textEdit_log.setTextColor(blackColor)

    # add thread here
    def continuous_reading(self):
        while (self.checkBox.isChecked()):
            self.slave_response = modbus_read_registers(modbus_function=4, register_address=30001, amount_of_read=5)
            self.lineEdit_errors.setText(str(self.slave_response[0]))
            self.lineEdit_angle.setText(str(self.slave_response[1]))
            self.lineEdit_speed.setText(str(self.slave_response[2]))
            self.lineEdit_torque.setText(str(self.slave_response[3]))
            self.temp = divmod(self.slave_response[4], 0x100)
            self.lineEdit_motortemp.setText(str(self.temp[1]))
            self.lineEdit_drivertemp.setText(str(self.temp[0]))
            time.sleep(0.01)

    def read_single_all_status_registers(self):
        if self.checkBox.isChecked():
            self.continuous_reading()
        else:
            self.slave_response = modbus_read_registers(modbus_function=4, register_address=30001, amount_of_read=5)
            self.lineEdit_errors.setText(str(self.slave_response[0]))
            self.lineEdit_angle.setText(str(self.slave_response[1]))
            self.lineEdit_speed.setText(str(self.slave_response[2]))
            self.lineEdit_torque.setText(str(self.slave_response[3]))
            self.temp = divmod(self.slave_response[4], 0x100)
            self.lineEdit_motortemp.setText(str(self.temp[1]))
            self.lineEdit_drivertemp.setText(str(self.temp[0]))
            self.textEdit_log.append(f"- {self.get_time()}: Slave response: {hex(self.slave_response[0])} {hex(self.slave_response[1])} "
                                     f"{hex(self.slave_response[2])} {hex(self.slave_response[3])} {hex(self.slave_response[4])}")

    def write_single_register(self):
        if  self.radioButton_targetangle.isChecked():
            print((self.dial_angle.value()*4))
            modbus_write_single((self.dial_angle.value()*4))


    def enable_motor(self):
        modbus_enable_motor(self.slaveidspinBox.value())

    def update_target_angle_lable(self):
        self.lineEdit_targetangle.setText(f"{self.dial_angle.value()/4096*360:.1f}°")
        # Plot.update_plot(self)
        if self.checkBox_follow.checkState():
            modbus_update_target_angle(self.dial_angle.value()*4)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
