# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'COM_Setting_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import serial
import sys
import glob



class Ui_COMSettingWindow(object):
    def setupUi(self, COMSettingWindow):
        COMSettingWindow.setObjectName("COMSettingWindow")
        COMSettingWindow.resize(700, 300)
        self.centralwidget = QtWidgets.QWidget(COMSettingWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(130, 20, 81, 22))
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 91, 20))
        self.label.setObjectName("label")
        COMSettingWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(COMSettingWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 21))
        self.menubar.setObjectName("menubar")
        COMSettingWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(COMSettingWindow)
        self.statusbar.setObjectName("statusbar")
        COMSettingWindow.setStatusBar(self.statusbar)

        self.retranslateUi(COMSettingWindow)
        QtCore.QMetaObject.connectSlotsByName(COMSettingWindow)

    def retranslateUi(self, COMSettingWindow):
        _translate = QtCore.QCoreApplication.translate
        COMSettingWindow.setWindowTitle(_translate("COMSettingWindow", "COM Settings"))
        self.label.setText(_translate("COMSettingWindow", "Select COM Port"))
        self.comboBox.addItem(self.list_com_ports()[0])
        self.comboBox.addItem(self.list_com_ports()[1])

    """ Lists serial port names

        :raises EnvironmentError:
            On unsupported or unknown platforms
        :returns:
            A list of the serial ports available on the system
    """

    def list_com_ports(self):
        if sys.platform.startswith('win'):
            ports = ['COM%s' % (i + 1) for i in range(256)]
        elif sys.platform.startswith('linux') or sys.platform.startswith('cygwin'):
            # this excludes your current terminal "/dev/tty"
            ports = glob.glob('/dev/tty[A-Za-z]*')
        elif sys.platform.startswith('darwin'):
            ports = glob.glob('/dev/tty.*')
        else:
            raise EnvironmentError('Unsupported platform')

        result = []
        for port in ports:
            try:
                s = serial.Serial(port)
                s.close()
                result.append(port)
            except (OSError, serial.SerialException):
                pass
        return result


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    COMSettingWindow = QtWidgets.QMainWindow()
    ui = Ui_COMSettingWindow()
    ui.setupUi(COMSettingWindow)
    COMSettingWindow.show()
    sys.exit(app.exec_())
