import time

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import numpy as np

from modbus import *
from COM_Setting_window import *
from plot import Plot


class Ui_MainWindow:
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1300, 850)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        MainWindow.setWindowOpacity(0.98)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Germany))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks|QtWidgets.QMainWindow.VerticalTabs)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.slaveidspinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.slaveidspinBox.setGeometry(QtCore.QRect(100, 10, 41, 20))
        self.slaveidspinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.slaveidspinBox.setProperty("value", 1)
        self.slaveidspinBox.setObjectName("slaveidspinBox")
        self.slaveidlable = QtWidgets.QLabel(self.centralwidget)
        self.slaveidlable.setGeometry(QtCore.QRect(20, 10, 70, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.slaveidlable.setFont(font)
        self.slaveidlable.setObjectName("slaveidlable")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(340, 210, 381, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(320, 10, 20, 661))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButton_readallstatus = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_readallstatus.setGeometry(QtCore.QRect(590, 170, 121, 21))
        self.pushButton_readallstatus.setObjectName("pushButton_readallstatus")
        self.textEdit_log = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_log.setGeometry(QtCore.QRect(20, 420, 291, 241))
        self.textEdit_log.setObjectName("textEdit_log")
        self.jcuinputreglable = QtWidgets.QLabel(self.centralwidget)
        self.jcuinputreglable.setEnabled(True)
        self.jcuinputreglable.setGeometry(QtCore.QRect(490, 10, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.jcuinputreglable.setFont(font)
        self.jcuinputreglable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.jcuinputreglable.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Germany))
        self.jcuinputreglable.setObjectName("jcuinputreglable")
        self.jcuholdreglable = QtWidgets.QLabel(self.centralwidget)
        self.jcuholdreglable.setEnabled(True)
        self.jcuholdreglable.setGeometry(QtCore.QRect(470, 230, 160, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.jcuholdreglable.setFont(font)
        self.jcuholdreglable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.jcuholdreglable.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Germany))
        self.jcuholdreglable.setObjectName("jcuholdreglable")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(720, 10, 20, 791))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.pushButton_readsinglestatus = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_readsinglestatus.setGeometry(QtCore.QRect(590, 40, 121, 21))
        self.pushButton_readsinglestatus.setObjectName("pushButton_readsinglestatus")
        self.pushButton_readsingleconfig = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_readsingleconfig.setGeometry(QtCore.QRect(590, 270, 121, 21))
        self.pushButton_readsingleconfig.setObjectName("pushButton_readsingleconfig")
        self.pushButton_readallconfig = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_readallconfig.setGeometry(QtCore.QRect(590, 620, 121, 21))
        self.pushButton_readallconfig.setObjectName("pushButton_readallconfig")
        self.pushButton_writeallconfig = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_writeallconfig.setGeometry(QtCore.QRect(590, 650, 121, 21))
        self.pushButton_writeallconfig.setObjectName("pushButton_writeallconfig")
        self.pushButton_writesingleconfig = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_writesingleconfig.setGeometry(QtCore.QRect(590, 300, 121, 21))
        self.pushButton_writesingleconfig.setObjectName("pushButton_writesingleconfig")
        self.lable_errors_2 = QtWidgets.QLabel(self.centralwidget)
        self.lable_errors_2.setGeometry(QtCore.QRect(20, 695, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lable_errors_2.setFont(font)
        self.lable_errors_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_errors_2.setObjectName("lable_errors_2")
        self.pushButton_enablemotor = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_enablemotor.setGeometry(QtCore.QRect(20, 90, 121, 21))
        self.pushButton_enablemotor.setObjectName("pushButton_enablemotor")
        self.dial_angle = QtWidgets.QDial(self.centralwidget)
        self.dial_angle.setGeometry(QtCore.QRect(20, 275, 121, 101))
        self.dial_angle.setInputMethodHints(QtCore.Qt.ImhNone)
        self.dial_angle.setMaximum(4095)
        self.dial_angle.setSingleStep(1)
        self.dial_angle.setPageStep(0)
        self.dial_angle.setOrientation(QtCore.Qt.Horizontal)
        self.dial_angle.setWrapping(True)
        self.dial_angle.setNotchTarget(90.0)
        self.dial_angle.setNotchesVisible(True)
        self.dial_angle.setObjectName("dial_angle")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(590, 140, 101, 20))
        self.checkBox.setObjectName("checkBox")
        self.pushButton_break = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_break.setGeometry(QtCore.QRect(20, 210, 121, 21))
        self.pushButton_break.setObjectName("pushButton_break")
        self.checkBox_follow = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_follow.setGeometry(QtCore.QRect(25, 380, 121, 20))
        self.checkBox_follow.setObjectName("checkBox_follow")
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(20, 150, 121, 21))
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_stop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_stop.setGeometry(QtCore.QRect(20, 180, 121, 21))
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.plot_widget_1 = QtWidgets.QWidget(self.centralwidget)
        self.plot_widget_1.setGeometry(QtCore.QRect(730, 20, 561, 221))
        self.plot_widget_1.setObjectName("plot_widget_1")
        self.plot_widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.plot_widget_2.setEnabled(False)
        self.plot_widget_2.setGeometry(QtCore.QRect(730, 260, 561, 221))
        self.plot_widget_2.setObjectName("plot_widget_2")
        self.plot_widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.plot_widget_3.setGeometry(QtCore.QRect(730, 500, 561, 221))
        self.plot_widget_3.setObjectName("plot_widget_3")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(361, 41, 211, 152))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_drivertemp = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_drivertemp.setText("")
        self.lineEdit_drivertemp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_drivertemp.setObjectName("lineEdit_drivertemp")
        self.gridLayout_3.addWidget(self.lineEdit_drivertemp, 5, 1, 1, 1)
        self.radioButton_drivertemp = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_drivertemp.setText("")
        self.radioButton_drivertemp.setObjectName("radioButton_drivertemp")
        self.gridLayout_3.addWidget(self.radioButton_drivertemp, 5, 2, 1, 1)
        self.lineEdit_errors = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_errors.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_errors.setText("")
        self.lineEdit_errors.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_errors.setObjectName("lineEdit_errors")
        self.gridLayout_3.addWidget(self.lineEdit_errors, 0, 1, 1, 1)
        self.lable_torque = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_torque.setFont(font)
        self.lable_torque.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_torque.setObjectName("lable_torque")
        self.gridLayout_3.addWidget(self.lable_torque, 3, 0, 1, 1)
        self.lineEdit_torque = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_torque.setText("")
        self.lineEdit_torque.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_torque.setObjectName("lineEdit_torque")
        self.gridLayout_3.addWidget(self.lineEdit_torque, 3, 1, 1, 1)
        self.radioButton_angle = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_angle.setText("")
        self.radioButton_angle.setObjectName("radioButton_angle")
        self.gridLayout_3.addWidget(self.radioButton_angle, 1, 2, 1, 1)
        self.radioButton_errors = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_errors.setText("")
        self.radioButton_errors.setCheckable(True)
        self.radioButton_errors.setChecked(False)
        self.radioButton_errors.setAutoRepeat(False)
        self.radioButton_errors.setObjectName("radioButton_errors")
        self.gridLayout_3.addWidget(self.radioButton_errors, 0, 2, 1, 1)
        self.radioButton_torque = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_torque.setText("")
        self.radioButton_torque.setObjectName("radioButton_torque")
        self.gridLayout_3.addWidget(self.radioButton_torque, 3, 2, 1, 1)
        self.lable_drivertemp = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_drivertemp.setFont(font)
        self.lable_drivertemp.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_drivertemp.setObjectName("lable_drivertemp")
        self.gridLayout_3.addWidget(self.lable_drivertemp, 5, 0, 1, 1)
        self.lable_speed = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_speed.setFont(font)
        self.lable_speed.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_speed.setObjectName("lable_speed")
        self.gridLayout_3.addWidget(self.lable_speed, 2, 0, 1, 1)
        self.lable_motortemp = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_motortemp.setFont(font)
        self.lable_motortemp.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_motortemp.setObjectName("lable_motortemp")
        self.gridLayout_3.addWidget(self.lable_motortemp, 4, 0, 1, 1)
        self.lable_errors = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_errors.setFont(font)
        self.lable_errors.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lable_errors.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_errors.setObjectName("lable_errors")
        self.gridLayout_3.addWidget(self.lable_errors, 0, 0, 1, 1)
        self.lineEdit_angle = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_angle.setText("")
        self.lineEdit_angle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_angle.setObjectName("lineEdit_angle")
        self.gridLayout_3.addWidget(self.lineEdit_angle, 1, 1, 1, 1)
        self.lineEdit_speed = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_speed.setText("")
        self.lineEdit_speed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_speed.setObjectName("lineEdit_speed")
        self.gridLayout_3.addWidget(self.lineEdit_speed, 2, 1, 1, 1)
        self.lable_angle = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lable_angle.sizePolicy().hasHeightForWidth())
        self.lable_angle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_angle.setFont(font)
        self.lable_angle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_angle.setObjectName("lable_angle")
        self.gridLayout_3.addWidget(self.lable_angle, 1, 0, 1, 1)
        self.radioButton_speed = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_speed.setText("")
        self.radioButton_speed.setObjectName("radioButton_speed")
        self.gridLayout_3.addWidget(self.radioButton_speed, 2, 2, 1, 1)
        self.lineEdit_motortemp = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_motortemp.setText("")
        self.lineEdit_motortemp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_motortemp.setObjectName("lineEdit_motortemp")
        self.gridLayout_3.addWidget(self.lineEdit_motortemp, 4, 1, 1, 1)
        self.radioButton_mottemp = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_mottemp.setText("")
        self.radioButton_mottemp.setObjectName("radioButton_mottemp")
        self.gridLayout_3.addWidget(self.radioButton_mottemp, 4, 2, 1, 1)
        self.pushButton_connect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_connect.setGeometry(QtCore.QRect(20, 40, 121, 21))
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.label_lamp_connected = QtWidgets.QLabel(self.centralwidget)
        self.label_lamp_connected.setGeometry(QtCore.QRect(160, 41, 20, 20))
        self.label_lamp_connected.setText("")
        self.label_lamp_connected.setPixmap(QtGui.QPixmap("D:\PROJECTS\PERSONAL\ROBOT_ARM\Software\JCU_GUI\pictures/grey_20x20.png"))
        self.label_lamp_connected.setAlignment(QtCore.Qt.AlignCenter)
        self.label_lamp_connected.setObjectName("label_lamp_connected")
        self.label_lamp_motoron = QtWidgets.QLabel(self.centralwidget)
        self.label_lamp_motoron.setGeometry(QtCore.QRect(160, 91, 20, 20))
        self.label_lamp_motoron.setText("")
        self.label_lamp_motoron.setPixmap(QtGui.QPixmap("D:\PROJECTS\PERSONAL\ROBOT_ARM\Software\JCU_GUI\pictures/grey_20x20.png"))
        self.label_lamp_motoron.setAlignment(QtCore.Qt.AlignCenter)
        self.label_lamp_motoron.setObjectName("label_lamp_motoron")
        self.pushButton_disablemotor = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_disablemotor.setGeometry(QtCore.QRect(20, 120, 121, 21))
        self.pushButton_disablemotor.setObjectName("pushButton_disablemotor")
        self.lable_icon_motoron = QtWidgets.QLabel(self.centralwidget)
        self.lable_icon_motoron.setGeometry(QtCore.QRect(190, 90, 89, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_icon_motoron.setFont(font)
        self.lable_icon_motoron.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_icon_motoron.setObjectName("lable_icon_motoron")
        self.lable_icon_connected = QtWidgets.QLabel(self.centralwidget)
        self.lable_icon_connected.setGeometry(QtCore.QRect(190, 40, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_icon_connected.setFont(font)
        self.lable_icon_connected.setTextFormat(QtCore.Qt.AutoText)
        self.lable_icon_connected.setScaledContents(False)
        self.lable_icon_connected.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_icon_connected.setObjectName("lable_icon_connected")
        self.label_lamp_motorrun = QtWidgets.QLabel(self.centralwidget)
        self.label_lamp_motorrun.setGeometry(QtCore.QRect(160, 151, 20, 20))
        self.label_lamp_motorrun.setText("")
        self.label_lamp_motorrun.setPixmap(QtGui.QPixmap("D:\PROJECTS\PERSONAL\ROBOT_ARM\Software\JCU_GUI\pictures/grey_20x20.png"))
        self.label_lamp_motorrun.setAlignment(QtCore.Qt.AlignCenter)
        self.label_lamp_motorrun.setObjectName("label_lamp_motorrun")
        self.lable_icon_motorrun = QtWidgets.QLabel(self.centralwidget)
        self.lable_icon_motorrun.setGeometry(QtCore.QRect(190, 150, 89, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_icon_motorrun.setFont(font)
        self.lable_icon_motorrun.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_icon_motorrun.setObjectName("lable_icon_motorrun")
        self.label_lamp_brakeset = QtWidgets.QLabel(self.centralwidget)
        self.label_lamp_brakeset.setGeometry(QtCore.QRect(160, 211, 20, 20))
        self.label_lamp_brakeset.setText("")
        self.label_lamp_brakeset.setPixmap(QtGui.QPixmap("D:\PROJECTS\PERSONAL\ROBOT_ARM\Software\JCU_GUI\pictures/grey_20x20.png"))
        self.label_lamp_brakeset.setAlignment(QtCore.Qt.AlignCenter)
        self.label_lamp_brakeset.setObjectName("label_lamp_brakeset")
        self.lable_icon_brakeset = QtWidgets.QLabel(self.centralwidget)
        self.lable_icon_brakeset.setGeometry(QtCore.QRect(190, 210, 89, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_icon_brakeset.setFont(font)
        self.lable_icon_brakeset.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_icon_brakeset.setObjectName("lable_icon_brakeset")
        self.label_error_mag = QtWidgets.QLabel(self.centralwidget)
        self.label_error_mag.setGeometry(QtCore.QRect(20, 721, 20, 20))
        self.label_error_mag.setText("")
        self.label_error_mag.setPixmap(QtGui.QPixmap("D:\PROJECTS\PERSONAL\ROBOT_ARM\Software\JCU_GUI\pictures/grey_20x20.png"))
        self.label_error_mag.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error_mag.setObjectName("label_error_mag")
        self.label_error_enc_par = QtWidgets.QLabel(self.centralwidget)
        self.label_error_enc_par.setGeometry(QtCore.QRect(20, 751, 20, 20))
        self.label_error_enc_par.setText("")
        self.label_error_enc_par.setPixmap(QtGui.QPixmap("D:\PROJECTS\PERSONAL\ROBOT_ARM\Software\JCU_GUI\pictures/grey_20x20.png"))
        self.label_error_enc_par.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error_enc_par.setObjectName("label_error_enc_par")
        self.label_lamp_reachedposition = QtWidgets.QLabel(self.centralwidget)
        self.label_lamp_reachedposition.setGeometry(QtCore.QRect(160, 181, 20, 20))
        self.label_lamp_reachedposition.setText("")
        self.label_lamp_reachedposition.setPixmap(QtGui.QPixmap("D:\PROJECTS\PERSONAL\ROBOT_ARM\Software\JCU_GUI\pictures/grey_20x20.png"))
        self.label_lamp_reachedposition.setAlignment(QtCore.Qt.AlignCenter)
        self.label_lamp_reachedposition.setObjectName("label_lamp_reachedposition")
        self.lable_icon_reachedposition = QtWidgets.QLabel(self.centralwidget)
        self.lable_icon_reachedposition.setGeometry(QtCore.QRect(190, 180, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_icon_reachedposition.setFont(font)
        self.lable_icon_reachedposition.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_icon_reachedposition.setObjectName("lable_icon_reachedposition")
        self.lable_settargetangle = QtWidgets.QLabel(self.centralwidget)
        self.lable_settargetangle.setGeometry(QtCore.QRect(30, 250, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lable_settargetangle.setFont(font)
        self.lable_settargetangle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_settargetangle.setObjectName("lable_settargetangle")
        self.label_lamp_loggingenabled = QtWidgets.QLabel(self.centralwidget)
        self.label_lamp_loggingenabled.setGeometry(QtCore.QRect(160, 251, 20, 20))
        self.label_lamp_loggingenabled.setText("")
        self.label_lamp_loggingenabled.setPixmap(QtGui.QPixmap("D:\PROJECTS\PERSONAL\ROBOT_ARM\Software\JCU_GUI\pictures/grey_20x20.png"))
        self.label_lamp_loggingenabled.setAlignment(QtCore.Qt.AlignCenter)
        self.label_lamp_loggingenabled.setObjectName("label_lamp_loggingenabled")
        self.lable_icon_loggingenabled = QtWidgets.QLabel(self.centralwidget)
        self.lable_icon_loggingenabled.setGeometry(QtCore.QRect(190, 250, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_icon_loggingenabled.setFont(font)
        self.lable_icon_loggingenabled.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_icon_loggingenabled.setObjectName("lable_icon_loggingenabled")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, 680, 711, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_error_enc_inc = QtWidgets.QLabel(self.centralwidget)
        self.label_error_enc_inc.setGeometry(QtCore.QRect(20, 781, 20, 20))
        self.label_error_enc_inc.setText("")
        self.label_error_enc_inc.setPixmap(QtGui.QPixmap("D:\PROJECTS\PERSONAL\ROBOT_ARM\Software\JCU_GUI\pictures/grey_20x20.png"))
        self.label_error_enc_inc.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error_enc_inc.setObjectName("label_error_enc_inc")
        self.lable_errors_3 = QtWidgets.QLabel(self.centralwidget)
        self.lable_errors_3.setGeometry(QtCore.QRect(50, 720, 201, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_errors_3.setFont(font)
        self.lable_errors_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_errors_3.setObjectName("lable_errors_3")
        self.lable_errors_4 = QtWidgets.QLabel(self.centralwidget)
        self.lable_errors_4.setGeometry(QtCore.QRect(50, 750, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_errors_4.setFont(font)
        self.lable_errors_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_errors_4.setObjectName("lable_errors_4")
        self.lable_errors_5 = QtWidgets.QLabel(self.centralwidget)
        self.lable_errors_5.setGeometry(QtCore.QRect(50, 780, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_errors_5.setFont(font)
        self.lable_errors_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_errors_5.setObjectName("lable_errors_5")
        self.label_error_modbus_crc = QtWidgets.QLabel(self.centralwidget)
        self.label_error_modbus_crc.setGeometry(QtCore.QRect(260, 721, 20, 20))
        self.label_error_modbus_crc.setText("")
        self.label_error_modbus_crc.setPixmap(QtGui.QPixmap("D:\PROJECTS\PERSONAL\ROBOT_ARM\Software\JCU_GUI\pictures/grey_20x20.png"))
        self.label_error_modbus_crc.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error_modbus_crc.setObjectName("label_error_modbus_crc")
        self.label_error_modbus_ex_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_error_modbus_ex_1.setGeometry(QtCore.QRect(260, 751, 20, 20))
        self.label_error_modbus_ex_1.setText("")
        self.label_error_modbus_ex_1.setPixmap(QtGui.QPixmap("D:\PROJECTS\PERSONAL\ROBOT_ARM\Software\JCU_GUI\pictures/grey_20x20.png"))
        self.label_error_modbus_ex_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error_modbus_ex_1.setObjectName("label_error_modbus_ex_1")
        self.label_error_modbus_ex_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_error_modbus_ex_2.setGeometry(QtCore.QRect(260, 781, 20, 20))
        self.label_error_modbus_ex_2.setText("")
        self.label_error_modbus_ex_2.setPixmap(QtGui.QPixmap("D:\PROJECTS\PERSONAL\ROBOT_ARM\Software\JCU_GUI\pictures/grey_20x20.png"))
        self.label_error_modbus_ex_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error_modbus_ex_2.setObjectName("label_error_modbus_ex_2")
        self.lable_errors_6 = QtWidgets.QLabel(self.centralwidget)
        self.lable_errors_6.setGeometry(QtCore.QRect(290, 720, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_errors_6.setFont(font)
        self.lable_errors_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_errors_6.setObjectName("lable_errors_6")
        self.lable_errors_7 = QtWidgets.QLabel(self.centralwidget)
        self.lable_errors_7.setGeometry(QtCore.QRect(290, 750, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_errors_7.setFont(font)
        self.lable_errors_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_errors_7.setObjectName("lable_errors_7")
        self.lable_errors_8 = QtWidgets.QLabel(self.centralwidget)
        self.lable_errors_8.setGeometry(QtCore.QRect(290, 780, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_errors_8.setFont(font)
        self.lable_errors_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_errors_8.setObjectName("lable_errors_8")
        self.lable_errors_9 = QtWidgets.QLabel(self.centralwidget)
        self.lable_errors_9.setGeometry(QtCore.QRect(530, 719, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_errors_9.setFont(font)
        self.lable_errors_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_errors_9.setObjectName("lable_errors_9")
        self.label_error_overtemp_motor = QtWidgets.QLabel(self.centralwidget)
        self.label_error_overtemp_motor.setGeometry(QtCore.QRect(500, 751, 20, 20))
        self.label_error_overtemp_motor.setText("")
        self.label_error_overtemp_motor.setPixmap(QtGui.QPixmap("D:\PROJECTS\PERSONAL\ROBOT_ARM\Software\JCU_GUI\pictures/grey_20x20.png"))
        self.label_error_overtemp_motor.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error_overtemp_motor.setObjectName("label_error_overtemp_motor")
        self.lable_errors_10 = QtWidgets.QLabel(self.centralwidget)
        self.lable_errors_10.setGeometry(QtCore.QRect(530, 779, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_errors_10.setFont(font)
        self.lable_errors_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_errors_10.setObjectName("lable_errors_10")
        self.label_error_overtemp_driver = QtWidgets.QLabel(self.centralwidget)
        self.label_error_overtemp_driver.setGeometry(QtCore.QRect(500, 721, 20, 20))
        self.label_error_overtemp_driver.setText("")
        self.label_error_overtemp_driver.setPixmap(QtGui.QPixmap("D:\PROJECTS\PERSONAL\ROBOT_ARM\Software\JCU_GUI\pictures/grey_20x20.png"))
        self.label_error_overtemp_driver.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error_overtemp_driver.setObjectName("label_error_overtemp_driver")
        self.lable_errors_11 = QtWidgets.QLabel(self.centralwidget)
        self.lable_errors_11.setGeometry(QtCore.QRect(530, 749, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_errors_11.setFont(font)
        self.lable_errors_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_errors_11.setObjectName("lable_errors_11")
        self.label_error_overcurrent = QtWidgets.QLabel(self.centralwidget)
        self.label_error_overcurrent.setGeometry(QtCore.QRect(500, 781, 20, 20))
        self.label_error_overcurrent.setText("")
        self.label_error_overcurrent.setPixmap(QtGui.QPixmap("D:\PROJECTS\PERSONAL\ROBOT_ARM\Software\JCU_GUI\pictures/grey_20x20.png"))
        self.label_error_overcurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error_overcurrent.setObjectName("label_label_error_overcurrent")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(456, 271, 121, 411))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_acceleration = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_acceleration.setText("")
        self.lineEdit_acceleration.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_acceleration.setObjectName("lineEdit_acceleration")
        self.gridLayout.addWidget(self.lineEdit_acceleration, 0, 0, 1, 1)
        self.radioButton_accel = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioButton_accel.setText("")
        self.radioButton_accel.setObjectName("radioButton_accel")
        self.gridLayout.addWidget(self.radioButton_accel, 0, 1, 2, 1)
        self.lineEdit_deceleration = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_deceleration.setText("")
        self.lineEdit_deceleration.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_deceleration.setObjectName("lineEdit_deceleration")
        self.gridLayout.addWidget(self.lineEdit_deceleration, 1, 0, 1, 1)
        self.lineEdit_maxspeed = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_maxspeed.setText("")
        self.lineEdit_maxspeed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_maxspeed.setObjectName("lineEdit_maxspeed")
        self.gridLayout.addWidget(self.lineEdit_maxspeed, 2, 0, 1, 1)
        self.lineEdit_ki_speed = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_ki_speed.setText("")
        self.lineEdit_ki_speed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_ki_speed.setObjectName("lineEdit_ki_speed")
        self.gridLayout.addWidget(self.lineEdit_ki_speed, 13, 0, 1, 1)
        self.radioButton_targetangle = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioButton_targetangle.setText("")
        self.radioButton_targetangle.setAutoExclusive(True)
        self.radioButton_targetangle.setObjectName("radioButton_targetangle")
        self.gridLayout.addWidget(self.radioButton_targetangle, 4, 1, 1, 1)
        self.lineEdit_statreg = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_statreg.setText("")
        self.lineEdit_statreg.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_statreg.setObjectName("lineEdit_statreg")
        self.gridLayout.addWidget(self.lineEdit_statreg, 5, 0, 1, 1)
        self.radioButton_kdposition = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioButton_kdposition.setText("")
        self.radioButton_kdposition.setObjectName("radioButton_kdposition")
        self.gridLayout.addWidget(self.radioButton_kdposition, 11, 1, 1, 1)
        self.radioButton_kispeed = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioButton_kispeed.setText("")
        self.radioButton_kispeed.setObjectName("radioButton_kispeed")
        self.gridLayout.addWidget(self.radioButton_kispeed, 13, 1, 1, 1)
        self.lineEdit_kd_pos = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_kd_pos.setText("")
        self.lineEdit_kd_pos.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_kd_pos.setObjectName("lineEdit_kd_pos")
        self.gridLayout.addWidget(self.lineEdit_kd_pos, 11, 0, 1, 1)
        self.radioButton_statusreg = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioButton_statusreg.setText("")
        self.radioButton_statusreg.setObjectName("radioButton_statusreg")
        self.gridLayout.addWidget(self.radioButton_statusreg, 5, 1, 1, 1)
        self.radioButton_kdcurrent = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioButton_kdcurrent.setEnabled(False)
        self.radioButton_kdcurrent.setText("")
        self.radioButton_kdcurrent.setObjectName("radioButton_kdcurrent")
        self.gridLayout.addWidget(self.radioButton_kdcurrent, 8, 1, 1, 1)
        self.lineEdit_kp_speed = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_kp_speed.setText("")
        self.lineEdit_kp_speed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_kp_speed.setObjectName("lineEdit_kp_speed")
        self.gridLayout.addWidget(self.lineEdit_kp_speed, 12, 0, 1, 1)
        self.lineEdit_kd_speed = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_kd_speed.setText("")
        self.lineEdit_kd_speed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_kd_speed.setObjectName("lineEdit_kd_speed")
        self.gridLayout.addWidget(self.lineEdit_kd_speed, 14, 0, 1, 1)
        self.lineEdit_targetangle = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_targetangle.setText("")
        self.lineEdit_targetangle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_targetangle.setObjectName("lineEdit_targetangle")
        self.gridLayout.addWidget(self.lineEdit_targetangle, 4, 0, 1, 1)
        self.radioButton_maxspeedtorque = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioButton_maxspeedtorque.setText("")
        self.radioButton_maxspeedtorque.setObjectName("radioButton_maxspeedtorque")
        self.gridLayout.addWidget(self.radioButton_maxspeedtorque, 2, 1, 2, 1)
        self.radioButton_kiposition = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioButton_kiposition.setText("")
        self.radioButton_kiposition.setObjectName("radioButton_kiposition")
        self.gridLayout.addWidget(self.radioButton_kiposition, 10, 1, 1, 1)
        self.radioButton_kpspeed = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioButton_kpspeed.setText("")
        self.radioButton_kpspeed.setObjectName("radioButton_kpspeed")
        self.gridLayout.addWidget(self.radioButton_kpspeed, 12, 1, 1, 1)
        self.lineEdit_ki_current = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_ki_current.setText("")
        self.lineEdit_ki_current.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_ki_current.setObjectName("lineEdit_ki_current")
        self.gridLayout.addWidget(self.lineEdit_ki_current, 7, 0, 1, 1)
        self.lineEdit_kp_current = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_kp_current.setText("")
        self.lineEdit_kp_current.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_kp_current.setObjectName("lineEdit_kp_current")
        self.gridLayout.addWidget(self.lineEdit_kp_current, 6, 0, 1, 1)
        self.lineEdit_maxtorque = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_maxtorque.setText("")
        self.lineEdit_maxtorque.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_maxtorque.setObjectName("lineEdit_maxtorque")
        self.gridLayout.addWidget(self.lineEdit_maxtorque, 3, 0, 1, 1)
        self.radioButton_kicurrent = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioButton_kicurrent.setText("")
        self.radioButton_kicurrent.setObjectName("radioButton_kicurrent")
        self.gridLayout.addWidget(self.radioButton_kicurrent, 7, 1, 1, 1)
        self.lineEdit_kp_pos = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_kp_pos.setText("")
        self.lineEdit_kp_pos.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_kp_pos.setObjectName("lineEdit_kp_pos")
        self.gridLayout.addWidget(self.lineEdit_kp_pos, 9, 0, 1, 1)
        self.lineEdit_ki_pos = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_ki_pos.setText("")
        self.lineEdit_ki_pos.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_ki_pos.setObjectName("lineEdit_ki_pos")
        self.gridLayout.addWidget(self.lineEdit_ki_pos, 10, 0, 1, 1)
        self.radioButton_kdspeed = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioButton_kdspeed.setText("")
        self.radioButton_kdspeed.setObjectName("radioButton_kdspeed")
        self.gridLayout.addWidget(self.radioButton_kdspeed, 14, 1, 1, 1)
        self.lineEdit_kd_current = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_kd_current.setEnabled(False)
        self.lineEdit_kd_current.setText("")
        self.lineEdit_kd_current.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_kd_current.setObjectName("lineEdit_kd_current")
        self.gridLayout.addWidget(self.lineEdit_kd_current, 8, 0, 1, 1)
        self.radioButton_kpposition = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioButton_kpposition.setText("")
        self.radioButton_kpposition.setObjectName("radioButton_kpposition")
        self.gridLayout.addWidget(self.radioButton_kpposition, 9, 1, 1, 1)
        self.radioButton_kpcurrent = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioButton_kpcurrent.setText("")
        self.radioButton_kpcurrent.setObjectName("radioButton_kpcurrent")
        self.gridLayout.addWidget(self.radioButton_kpcurrent, 6, 1, 1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(361, 271, 91, 401))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lable_acceleration = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_acceleration.setFont(font)
        self.lable_acceleration.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_acceleration.setObjectName("lable_acceleration")
        self.verticalLayout.addWidget(self.lable_acceleration)
        self.lable_deceleration = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_deceleration.setFont(font)
        self.lable_deceleration.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_deceleration.setObjectName("lable_deceleration")
        self.verticalLayout.addWidget(self.lable_deceleration)
        self.lable_maxspeed = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_maxspeed.setFont(font)
        self.lable_maxspeed.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_maxspeed.setObjectName("lable_maxspeed")
        self.verticalLayout.addWidget(self.lable_maxspeed)
        self.lable_maxtorque = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_maxtorque.setFont(font)
        self.lable_maxtorque.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_maxtorque.setObjectName("lable_maxtorque")
        self.verticalLayout.addWidget(self.lable_maxtorque)
        self.lable_targetangle = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_targetangle.setFont(font)
        self.lable_targetangle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_targetangle.setObjectName("lable_targetangle")
        self.verticalLayout.addWidget(self.lable_targetangle)
        self.lable_statreg = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_statreg.setFont(font)
        self.lable_statreg.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_statreg.setObjectName("lable_statreg")
        self.verticalLayout.addWidget(self.lable_statreg)
        self.lable_kp_current = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_kp_current.setFont(font)
        self.lable_kp_current.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_kp_current.setObjectName("lable_kp_current")
        self.verticalLayout.addWidget(self.lable_kp_current)
        self.lable_ki_current = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_ki_current.setFont(font)
        self.lable_ki_current.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_ki_current.setObjectName("lable_ki_current")
        self.verticalLayout.addWidget(self.lable_ki_current)
        self.lable_kd_current = QtWidgets.QLabel(self.layoutWidget2)
        self.lable_kd_current.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_kd_current.setFont(font)
        self.lable_kd_current.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_kd_current.setObjectName("lable_kd_current")
        self.verticalLayout.addWidget(self.lable_kd_current)
        self.lable_kp_pos = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_kp_pos.setFont(font)
        self.lable_kp_pos.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_kp_pos.setObjectName("lable_kp_pos")
        self.verticalLayout.addWidget(self.lable_kp_pos)
        self.lable_ki_pos = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_ki_pos.setFont(font)
        self.lable_ki_pos.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_ki_pos.setObjectName("lable_ki_pos")
        self.verticalLayout.addWidget(self.lable_ki_pos)
        self.lable_kd_pos = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_kd_pos.setFont(font)
        self.lable_kd_pos.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_kd_pos.setObjectName("lable_kd_pos")
        self.verticalLayout.addWidget(self.lable_kd_pos)
        self.lable_kp_speed = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_kp_speed.setFont(font)
        self.lable_kp_speed.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_kp_speed.setObjectName("lable_kp_speed")
        self.verticalLayout.addWidget(self.lable_kp_speed)
        self.lable_ki_speed = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_ki_speed.setFont(font)
        self.lable_ki_speed.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_ki_speed.setObjectName("lable_ki_speed")
        self.verticalLayout.addWidget(self.lable_ki_speed)
        self.lable_kd_speed = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_kd_speed.setFont(font)
        self.lable_kd_speed.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_kd_speed.setObjectName("lable_kd_speed")
        self.verticalLayout.addWidget(self.lable_kd_speed)
        self.label_lamp_TBD_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_lamp_TBD_1.setGeometry(QtCore.QRect(160, 281, 20, 20))
        self.label_lamp_TBD_1.setText("")
        self.label_lamp_TBD_1.setPixmap(QtGui.QPixmap("D:\PROJECTS\PERSONAL\ROBOT_ARM\Software\JCU_GUI\pictures/grey_20x20.png"))
        self.label_lamp_TBD_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_lamp_TBD_1.setObjectName("label_lamp_TBD_1")
        self.label_lamp_TBD_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_lamp_TBD_2.setGeometry(QtCore.QRect(160, 311, 20, 20))
        self.label_lamp_TBD_2.setText("")
        self.label_lamp_TBD_2.setPixmap(QtGui.QPixmap("D:\PROJECTS\PERSONAL\ROBOT_ARM\Software\JCU_GUI\pictures/grey_20x20.png"))
        self.label_lamp_TBD_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_lamp_TBD_2.setObjectName("label_lamp_TBD_2")
        self.label_lamp_TBD_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_lamp_TBD_3.setGeometry(QtCore.QRect(160, 341, 20, 20))
        self.label_lamp_TBD_3.setText("")
        self.label_lamp_TBD_3.setPixmap(QtGui.QPixmap("D:\PROJECTS\PERSONAL\ROBOT_ARM\Software\JCU_GUI\pictures/grey_20x20.png"))
        self.label_lamp_TBD_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_lamp_TBD_3.setObjectName("label_lamp_TBD_3")
        self.lable_icon_TBD_1 = QtWidgets.QLabel(self.centralwidget)
        self.lable_icon_TBD_1.setGeometry(QtCore.QRect(190, 280, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_icon_TBD_1.setFont(font)
        self.lable_icon_TBD_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_icon_TBD_1.setObjectName("lable_icon_TBD_1")
        self.lable_icon_TBD_2 = QtWidgets.QLabel(self.centralwidget)
        self.lable_icon_TBD_2.setGeometry(QtCore.QRect(190, 310, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_icon_TBD_2.setFont(font)
        self.lable_icon_TBD_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_icon_TBD_2.setObjectName("lable_icon_TBD_2")
        self.lable_icon_TBD_3 = QtWidgets.QLabel(self.centralwidget)
        self.lable_icon_TBD_3.setGeometry(QtCore.QRect(190, 340, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lable_icon_TBD_3.setFont(font)
        self.lable_icon_TBD_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_icon_TBD_3.setObjectName("lable_icon_TBD_3")
        self.comboBox_plot_1 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_plot_1.setGeometry(QtCore.QRect(750, 770, 91, 22))
        self.comboBox_plot_1.setObjectName("comboBox_plot_1")
        self.comboBox_plot_1.addItem("")
        self.comboBox_plot_1.addItem("")
        self.comboBox_plot_1.addItem("")
        self.comboBox_plot_1.addItem("")
        self.comboBox_plot_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_plot_2.setGeometry(QtCore.QRect(870, 770, 91, 22))
        self.comboBox_plot_2.setObjectName("comboBox_plot_2")
        self.comboBox_plot_2.addItem("")
        self.comboBox_plot_2.addItem("")
        self.comboBox_plot_2.addItem("")
        self.comboBox_plot_2.addItem("")
        self.comboBox_plot_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_plot_3.setGeometry(QtCore.QRect(990, 770, 91, 22))
        self.comboBox_plot_3.setObjectName("comboBox_plot_3")
        self.comboBox_plot_3.addItem("")
        self.comboBox_plot_3.addItem("")
        self.comboBox_plot_3.addItem("")
        self.comboBox_plot_3.addItem("")
        self.lable_plot_1 = QtWidgets.QLabel(self.centralwidget)
        self.lable_plot_1.setGeometry(QtCore.QRect(750, 745, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lable_plot_1.setFont(font)
        self.lable_plot_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_plot_1.setObjectName("lable_plot_1")
        self.lable_plot_2 = QtWidgets.QLabel(self.centralwidget)
        self.lable_plot_2.setGeometry(QtCore.QRect(870, 745, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lable_plot_2.setFont(font)
        self.lable_plot_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_plot_2.setObjectName("lable_plot_2")
        self.lable_plot_3 = QtWidgets.QLabel(self.centralwidget)
        self.lable_plot_3.setGeometry(QtCore.QRect(990, 745, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lable_plot_3.setFont(font)
        self.lable_plot_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lable_plot_3.setObjectName("lable_plot_3")
        self.pushButton_stopplots = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_stopplots.setGeometry(QtCore.QRect(1160, 770, 111, 22))
        self.pushButton_stopplots.setObjectName("pushButton_stopplots")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1300, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuLog = QtWidgets.QMenu(self.menubar)
        self.menuLog.setObjectName("menuLog")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAbout_2 = QtWidgets.QAction(MainWindow)
        self.actionAbout_2.setObjectName("actionAbout_2")
        self.actionSerial_config = QtWidgets.QAction(MainWindow)
        self.actionSerial_config.setObjectName("actionSerial_config")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionJCU_Register_Info = QtWidgets.QAction(MainWindow)
        self.actionJCU_Register_Info.setObjectName("actionJCU_Register_Info")
        self.actionJCU_Register_Info_2 = QtWidgets.QAction(MainWindow)
        self.actionJCU_Register_Info_2.setObjectName("actionJCU_Register_Info_2")
        self.actionRESET_JCU = QtWidgets.QAction(MainWindow)
        self.actionRESET_JCU.setObjectName("actionRESET_JCU")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout_3 = QtWidgets.QAction(MainWindow)
        self.actionAbout_3.setObjectName("actionAbout_3")
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addAction(self.actionJCU_Register_Info)
        self.menuFile.addAction(self.actionJCU_Register_Info_2)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionRESET_JCU)
        self.menuLog.addAction(self.actionHelp)
        self.menuAbout.addAction(self.actionAbout_3)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuLog.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Joint Control Unit GUI"))
        self.slaveidlable.setText(_translate("MainWindow", "Slave ID:"))
        self.pushButton_readallstatus.setText(_translate("MainWindow", "Read All"))
        self.jcuinputreglable.setText(_translate("MainWindow", "JCU Status"))
        self.jcuholdreglable.setText(_translate("MainWindow", "JCU Configuration"))
        self.pushButton_readsinglestatus.setText(_translate("MainWindow", "Read Single"))
        self.pushButton_readsingleconfig.setText(_translate("MainWindow", "Read Single"))
        self.pushButton_readallconfig.setText(_translate("MainWindow", "Read All"))
        self.pushButton_writeallconfig.setText(_translate("MainWindow", "Write All"))
        self.pushButton_writesingleconfig.setText(_translate("MainWindow", "Write Single"))
        self.lable_errors_2.setText(_translate("MainWindow", "Errors:"))
        self.pushButton_enablemotor.setText(_translate("MainWindow", "Enable Motor"))
        self.checkBox.setText(_translate("MainWindow", "Continious Read"))
        self.pushButton_break.setText(_translate("MainWindow", "Brake"))
        self.checkBox_follow.setText(_translate("MainWindow", "Follow in Real Time"))
        self.pushButton_start.setText(_translate("MainWindow", "Start"))
        self.pushButton_stop.setText(_translate("MainWindow", "Stop"))
        self.lable_torque.setText(_translate("MainWindow", "Torque"))
        self.lable_drivertemp.setText(_translate("MainWindow", "Driver temp"))
        self.lable_speed.setText(_translate("MainWindow", "Speed"))
        self.lable_motortemp.setText(_translate("MainWindow", "Motor temp     "))
        self.lable_errors.setText(_translate("MainWindow", "Errors"))
        self.lable_angle.setText(_translate("MainWindow", "Angle"))
        self.pushButton_connect.setText(_translate("MainWindow", "Connect"))
        self.pushButton_disablemotor.setText(_translate("MainWindow", "Disable Motor"))
        self.lable_icon_motoron.setText(_translate("MainWindow", "Motor ON"))
        self.lable_icon_connected.setText(_translate("MainWindow", "<html><head/><body><p>Connected</p></body></html>"))
        self.lable_icon_motorrun.setText(_translate("MainWindow", "Motor Run"))
        self.lable_icon_brakeset.setText(_translate("MainWindow", "Brake Set"))
        self.lable_icon_reachedposition.setText(_translate("MainWindow", "Reached Position"))
        self.lable_settargetangle.setText(_translate("MainWindow", "Set Target Angle"))
        self.lable_icon_loggingenabled.setText(_translate("MainWindow", "Logging Enabled"))
        self.lable_errors_3.setText(_translate("MainWindow", "Encoder\'s Magnetic Field Error"))
        self.lable_errors_4.setText(_translate("MainWindow", "Encoder\'s Parity Error"))
        self.lable_errors_5.setText(_translate("MainWindow", "Incremental Encoder Error"))
        self.lable_errors_6.setText(_translate("MainWindow", "Modbus Check Sum Error"))
        self.lable_errors_7.setText(_translate("MainWindow", "Modbus Illigal Function"))
        self.lable_errors_8.setText(_translate("MainWindow", "Modbus Illigal Data Address"))
        self.lable_errors_9.setText(_translate("MainWindow", "JCU Overtemperature"))
        self.lable_errors_10.setText(_translate("MainWindow", "Overcurrent"))
        self.lable_errors_11.setText(_translate("MainWindow", "Motor Overtemperature"))
        self.lable_acceleration.setText(_translate("MainWindow", "Acceleration"))
        self.lable_deceleration.setText(_translate("MainWindow", "Deceleration"))
        self.lable_maxspeed.setText(_translate("MainWindow", "Max speed"))
        self.lable_maxtorque.setText(_translate("MainWindow", "Max torque"))
        self.lable_targetangle.setText(_translate("MainWindow", "Target Angle"))
        self.lable_statreg.setText(_translate("MainWindow", "Status register"))
        self.lable_kp_current.setText(_translate("MainWindow", "Kp (current)"))
        self.lable_ki_current.setText(_translate("MainWindow", "Ki (current)"))
        self.lable_kd_current.setText(_translate("MainWindow", "Kd (current)"))
        self.lable_kp_pos.setText(_translate("MainWindow", "Kp (position)"))
        self.lable_ki_pos.setText(_translate("MainWindow", "Ki (position)"))
        self.lable_kd_pos.setText(_translate("MainWindow", "Kd (position)"))
        self.lable_kp_speed.setText(_translate("MainWindow", "Kp (speed)"))
        self.lable_ki_speed.setText(_translate("MainWindow", "Ki (speed)"))
        self.lable_kd_speed.setText(_translate("MainWindow", "Kd (speed)"))
        self.lable_icon_TBD_1.setText(_translate("MainWindow", "TBD"))
        self.lable_icon_TBD_2.setText(_translate("MainWindow", "TBD"))
        self.lable_icon_TBD_3.setText(_translate("MainWindow", "TBD"))
        self.comboBox_plot_1.setItemText(0, _translate("MainWindow", "Position"))
        self.comboBox_plot_1.setItemText(1, _translate("MainWindow", "Speed"))
        self.comboBox_plot_1.setItemText(2, _translate("MainWindow", "Torque"))
        self.comboBox_plot_1.setItemText(3, _translate("MainWindow", "Temperature"))
        self.comboBox_plot_2.setItemText(0, _translate("MainWindow", "Position"))
        self.comboBox_plot_2.setItemText(1, _translate("MainWindow", "Speed"))
        self.comboBox_plot_2.setItemText(2, _translate("MainWindow", "Torque"))
        self.comboBox_plot_2.setItemText(3, _translate("MainWindow", "Temperature"))
        self.comboBox_plot_3.setItemText(0, _translate("MainWindow", "Position"))
        self.comboBox_plot_3.setItemText(1, _translate("MainWindow", "Speed"))
        self.comboBox_plot_3.setItemText(2, _translate("MainWindow", "Torque"))
        self.comboBox_plot_3.setItemText(3, _translate("MainWindow", "Temperature"))
        self.lable_plot_1.setText(_translate("MainWindow", "Plot 1:"))
        self.lable_plot_2.setText(_translate("MainWindow", "Plot 2:"))
        self.lable_plot_3.setText(_translate("MainWindow", "Plot 3:"))
        self.pushButton_stopplots.setText(_translate("MainWindow", "Stop Plots"))
        self.menuFile.setTitle(_translate("MainWindow", "Options"))
        self.menuLog.setTitle(_translate("MainWindow", "Help"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAbout_2.setText(_translate("MainWindow", "About"))
        self.actionSerial_config.setText(_translate("MainWindow", "Serial config"))
        self.actionSettings.setText(_translate("MainWindow", "COM Settings"))
        self.actionJCU_Register_Info.setText(_translate("MainWindow", "LOG Settings"))
        self.actionJCU_Register_Info_2.setText(_translate("MainWindow", "JCU Register Info"))
        self.actionRESET_JCU.setText(_translate("MainWindow", "Reset JCU"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionAbout_3.setText(_translate("MainWindow", "About"))

##############################################################################################
##########                 End of Autogenerated code                              ############
##############################################################################################

        # user code begins here

        self.my_plot = Plot(self.plot_widget_1)

        # default values:
        self.lineEdit_targetangle.setPlaceholderText("0°")
        self.textEdit_log.setPlaceholderText("Log...")
        self.comboBox_plot_1.setCurrentIndex(0)
        self.comboBox_plot_2.setCurrentIndex(1)
        self.comboBox_plot_3.setCurrentIndex(2)
        self.com_port_connected = 0

        # Signals:
        self.pushButton_enablemotor.clicked.connect(self.enable_motor)
        self.dial_angle.valueChanged.connect(self.update_target_angle_lable)
        self.pushButton_connect.clicked.connect(self.connect_device)
        self.pushButton_readsinglestatus.clicked.connect(self.read_single_status_register)
        self.pushButton_readallstatus.clicked.connect(self.read_single_all_status_registers)
        self.pushButton_writesingleconfig.clicked.connect(self.write_single_register)
        self.lineEdit_targetangle.editingFinished.connect(self.place_angle_mark)
        self.actionSettings.triggered.connect(self.open_comport_setting)

    def get_time(self):
        """Function of getting real time"""
        # self.currenttime = time.strftime("%H:%M:%S", time.localtime())
        self.currenttime = QtCore.QTime.currentTime().toString("hh:mm:ss.zzz")
        return self.currenttime

    def connect_device(self):
        """Function of creatin comport connection with JCU"""
        # check if we have already selected this comport
        if self.com_port_connected == 0:
            # check if chosen COM port available
            if check_com():
                self.label_lamp_connected.setPixmap(QtGui.QPixmap("D:\PROJECTS\PERSONAL\ROBOT_ARM\Software\JCU_GUI\pictures/green_20x20.png"))
                # connect to this COM port with MODBUS
                self.com_port_connected = 1
                open_com()
                self.textEdit_log.append(f"- {self.get_time()}: Device 01 has been connected")
            else:
                # something wrong with COM port
                self.label_lamp_connected.setPixmap(QtGui.QPixmap("D:\PROJECTS\PERSONAL\ROBOT_ARM\Software\JCU_GUI\pictures/red_20x20.png"))

        # self.my_plot.update_plot()

    def read_single_status_register(self):
        """
        * Reading and parcing information from JCU
        * Reading of single register
        """
        if self.radioButton_errors.isChecked():
            self.slave_response = modbus_read_registers(modbus_function = 4, register_address = 30001, amount_of_read = 1)
            self.textEdit_log.append(f"- {self.get_time()}: Slave response: {hex(self.slave_response[0])}")
            self.lineEdit_errors.setText(f"{self.slave_response[0]}")
            self.error_parcing(self.slave_response[0])

        elif self.radioButton_angle.isChecked():
            self.slave_response = modbus_read_registers(modbus_function = 4, register_address = 30002, amount_of_read = 1)
            self.textEdit_log.append(f"- {self.get_time()}: Slave response: {hex(self.slave_response[0])}")
            self.lineEdit_angle.setText(f"{self.slave_response[0]}")

        elif self.radioButton_speed.isChecked():
            self.slave_response = modbus_read_registers(modbus_function = 4, register_address = 30003, amount_of_read = 1)
            self.textEdit_log.append(f"- {self.get_time()}: Slave response: {hex(self.slave_response[0])}")
            self.lineEdit_speed.setText(f"{self.slave_response[0]}")

        elif self.radioButton_torque.isChecked():
            self.slave_response = modbus_read_registers(modbus_function = 4, register_address = 30004, amount_of_read = 1)
            self.textEdit_log.append(f"- {self.get_time()}: Slave response: {hex(self.slave_response[0])}")
            self.lineEdit_torque.setText(f"{self.slave_response[0]}")

        elif self.radioButton_mottemp.isChecked():
            self.slave_response = modbus_read_registers(modbus_function = 4, register_address = 30005, amount_of_read = 1)
            self.temp = divmod(self.slave_response[0], 0x100)
            self.textEdit_log.append(f"- {self.get_time()}: Slave response: {hex(self.slave_response[0])}")
            self.lineEdit_motortemp.setText(str(self.temp[1]))
            self.lineEdit_drivertemp.setText(str(self.temp[0]))
        else:
            msg = QMessageBox()
            msg.setWindowTitle("Incorrect request")
            msg.setText("Please, select register you want to read!")
            msg.setIcon(QMessageBox.Warning)
            x = msg.exec_()
            # self.textEdit_log.setTextColor(redColor)
            # self.textEdit_log.append(f"- {self.get_time()}: Select register to read!")
            # self.textEdit_log.setTextColor(blackColor)

    # ADD THREAD HERE
    def continuous_reading(self):
        """Implementation of continiuos reading of data from JCU"""
        while (self.checkBox.isChecked()):
            self.slave_response = modbus_read_registers(modbus_function=4, register_address=30001, amount_of_read=5)
            self.lineEdit_errors.setText(str(self.slave_response[0]))
            self.lineEdit_angle.setText(str(self.slave_response[1]))
            self.lineEdit_speed.setText(str(self.slave_response[2]))
            self.lineEdit_torque.setText(str(self.slave_response[3]))
            self.temp = divmod(self.slave_response[4], 0x100)
            self.lineEdit_motortemp.setText(str(self.temp[1]))
            self.lineEdit_drivertemp.setText(str(self.temp[0]))
            time.sleep(0.003)

    def read_single_all_status_registers(self):
        """
        * Reading and parcing information from JCU
        * Reading of ALL registers
        """
        if self.checkBox.isChecked():
            self.continuous_reading()
        else:
            self.slave_response = modbus_read_registers(modbus_function=4, register_address=30001, amount_of_read=5)
            self.lineEdit_errors.setText(str(self.slave_response[0]))
            self.error_parcing(self.slave_response[0])
            self.lineEdit_angle.setText(str(self.slave_response[1]))
            self.lineEdit_speed.setText(str(self.slave_response[2]))
            self.lineEdit_torque.setText(str(self.slave_response[3]))
            self.temp = divmod(self.slave_response[4], 0x100)
            self.lineEdit_motortemp.setText(str(self.temp[1]))
            self.lineEdit_drivertemp.setText(str(self.temp[0]))
            self.textEdit_log.append(f"- {self.get_time()}: Slave response: {hex(self.slave_response[0])} {hex(self.slave_response[1])} "
                                     f"{hex(self.slave_response[2])} {hex(self.slave_response[3])} {hex(self.slave_response[4])}")

    def error_parcing(self, error_register):
        # convert read register into binary string
        error_register_bin = "{0:b}".format(error_register)
        # fill all bits from left with zeroes, also reverse string, because indexing LSB
        error_register_bin = error_register_bin.zfill(16)[::-1]
        if error_register_bin[0] == '1':
            self.label_error_mag.setPixmap(QtGui.QPixmap("D:\PROJECTS\PERSONAL\ROBOT_ARM\Software\JCU_GUI\pictures/red_20x20.png"))
        else:
            self.label_error_mag.setPixmap(QtGui.QPixmap("D:\PROJECTS\PERSONAL\ROBOT_ARM\Software\JCU_GUI\pictures/grey_20x20.png"))
        if error_register_bin[1] == '1':
            self.label_error_enc_par.setPixmap(QtGui.QPixmap("D:\PROJECTS\PERSONAL\ROBOT_ARM\Software\JCU_GUI\pictures/red_20x20.png"))
        else:
            self.label_error_enc_par.setPixmap(QtGui.QPixmap("D:\PROJECTS\PERSONAL\ROBOT_ARM\Software\JCU_GUI\pictures/grey_20x20.png"))
        if error_register_bin[2] == '1':
            self.label_error_enc_inc.setPixmap(QtGui.QPixmap("D:\PROJECTS\PERSONAL\ROBOT_ARM\Software\JCU_GUI\pictures/red_20x20.png"))
        else:
            self.label_error_enc_inc.setPixmap(QtGui.QPixmap("D:\PROJECTS\PERSONAL\ROBOT_ARM\Software\JCU_GUI\pictures/grey_20x20.png"))
        if error_register_bin[3] == '1':
            pass #TBD
        else:
            pass #TBD
        if error_register_bin[4] == '1':
            self.label_error_modbus_crc.setPixmap(QtGui.QPixmap("D:\PROJECTS\PERSONAL\ROBOT_ARM\Software\JCU_GUI\pictures/red_20x20.png"))
        else:
            self.label_error_modbus_crc.setPixmap(QtGui.QPixmap("D:\PROJECTS\PERSONAL\ROBOT_ARM\Software\JCU_GUI\pictures/grey_20x20.png"))
        if error_register_bin[5] == '1':
            self.label_error_modbus_ex_1.setPixmap(QtGui.QPixmap("D:\PROJECTS\PERSONAL\ROBOT_ARM\Software\JCU_GUI\pictures/red_20x20.png"))
        else:
            self.label_error_modbus_ex_1.setPixmap(QtGui.QPixmap("D:\PROJECTS\PERSONAL\ROBOT_ARM\Software\JCU_GUI\pictures/grey_20x20.png"))
        if error_register_bin[6] == '1':
            self.label_error_modbus_ex_2.setPixmap(QtGui.QPixmap("D:\PROJECTS\PERSONAL\ROBOT_ARM\Software\JCU_GUI\pictures/red_20x20.png"))
        else:
            self.label_error_modbus_ex_2.setPixmap(QtGui.QPixmap("D:\PROJECTS\PERSONAL\ROBOT_ARM\Software\JCU_GUI\pictures/grey_20x20.png"))
        if error_register_bin[7] == '1':
            pass # Modbus Illegal Data Value
        else:
            pass # Modbus Illegal Data Value
        if error_register_bin[8] == '1':
            pass # Modbus Slave device failure
        else:
            pass # Modbus Slave device failure
        if error_register_bin[9] == '1':
            self.label_error_overcurrent.setPixmap(QtGui.QPixmap("D:\PROJECTS\PERSONAL\ROBOT_ARM\Software\JCU_GUI\pictures/red_20x20.png"))
        else:
            self.label_error_overcurrent.setPixmap(QtGui.QPixmap("D:\PROJECTS\PERSONAL\ROBOT_ARM\Software\JCU_GUI\pictures/grey_20x20.png"))
        if error_register_bin[10] == '1':
            self.label_error_overtemp_motor.setPixmap(QtGui.QPixmap("D:\PROJECTS\PERSONAL\ROBOT_ARM\Software\JCU_GUI\pictures/red_20x20.png"))
        else:
            self.label_error_overtemp_motor.setPixmap(QtGui.QPixmap("D:\PROJECTS\PERSONAL\ROBOT_ARM\Software\JCU_GUI\pictures/grey_20x20.png"))
        if error_register_bin[11] == '1':
            self.label_error_overtemp_driver.setPixmap(QtGui.QPixmap("D:\PROJECTS\PERSONAL\ROBOT_ARM\Software\JCU_GUI\pictures/red_20x20.png"))
        else:
            self.label_error_overtemp_driver.setPixmap(QtGui.QPixmap("D:\PROJECTS\PERSONAL\ROBOT_ARM\Software\JCU_GUI\pictures/grey_20x20.png"))


    def write_single_register(self):
        """
        * Writing information to JCU
        * Writing single registers
        """
        if  self.radioButton_targetangle.isChecked():
            print((self.dial_angle.value()*4))
            modbus_write_single((self.dial_angle.value()*4))

    def enable_motor(self):
        """Enable motor"""
        if self.com_port_connected:
            modbus_enable_motor(self.slaveidspinBox.value())
            self.label_lamp_motoron.setPixmap(QtGui.QPixmap("D:\PROJECTS\PERSONAL\ROBOT_ARM\Software\JCU_GUI\pictures/green_20x20.png"))

    def update_target_angle_lable(self):
        """Process event of changing Dial"""
        self.lineEdit_targetangle.setText(f"{self.dial_angle.value()/4096*360:.1f}°")
        if self.checkBox_follow.checkState():
            modbus_update_target_angle(self.dial_angle.value()*4)

        self.my_plot.update_plot()

    def place_angle_mark(self):
        """Cosmetic function to add angle mark at the end of the Target Angle's line"""
        # check if line is not empty, to avoid crashing
        if self.lineEdit_targetangle.text() != '':
            # check if it was already added
            self.last_char = self.lineEdit_targetangle.text()[-1]
            # add, if not
            if self.last_char != "°":
                self.lineEdit_targetangle.setText(f"{self.lineEdit_targetangle.text()}°")

    def open_comport_setting(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_COMSettingWindow()
        self.ui.setupUi(self.window)
        self.window.show()